[project]
name = "Callable Tools"
version = "0.1.0"
description = "A Framework for ez creation of functions that can be called remotely"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.5.8",
    "aiomqtt>=2.5.0",
    "dotenv>=0.9.9",
    "pydantic>=2.12.5",
]
